### ISSUE TITLE
default branch

### ISSUE THREAD

**Issue by sensorario** [sensorario/ff#56]
- [ ] ask user if prefers main or master branch name
 - [ ] when repo is created, ask if default branch is master or main
 - [ ] if not defined, ask what is the default branch
 - [ ] protect default branch forcing feature branches and so on
 - [ ] trying to commit on default branch, if protected, propose feature/ or other kind of branches
